apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codegen-100303-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/codegen-100303/overlays/development
    repoURL: https://github.com/fpetk/codegen-100303-gitops.git
    targetRevision: main
  destination:
    server: https://api.tpetkos-aicluster01.devcluster.openshift.com:6443
    namespace: ai-software-templates-dev
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
