apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-100303
  janus-idp.io/tekton: codegen-100303
  backstage.io/kubernetes-id: codegen-100303
  backstage.io/kubernetes-namespace: ai-software-templates-dev
  app.kubernetes.io/part-of: codegen-100303
resources:
- application-dev.yaml
- application-tekton.yaml